NumberOfDay field on Planning Page is a Number Only
gmojunior/PontoFacil pull request #19
Opened 2017-10-02 14:41 UTC by thiago-rocha

2017-10-02 16:25 UTC, soutolucas requested changes

2017-10-02 16:25 UTC, soutolucas commented on PontoFacil/PontoFacil/ViewModels/PlanningPageViewModel.cs
> +            return double.TryParse(sender, out double dtemp) && sender != "";
Use string.IsNullOrWhiteSpace instead of != ""

2017-10-02 16:25 UTC, soutolucas commented on PontoFacil/PontoFacil/Views/PlanningPage.xaml
> +                <TextBlock Grid.Column="0" Grid.Row="3" x:Uid="StartDay" />
Remove space

2017-10-02 17:05 UTC, thiago-rocha commented
@soutolucas ready to review.

2017-10-02 21:04 UTC, gmojunior requested changes

2017-10-02 21:04 UTC, gmojunior commented on PontoFacil/PontoFacil/ViewModels/PlanningPageViewModel.cs
> +            return double.TryParse(text, out double dtemp) && !string.IsNullOrWhiteSpace(text);
This !string.IsNullOrWhiteSpace(text) should be done first.

2017-10-02 21:04 UTC, gmojunior commented on PontoFacil/PontoFacil/ViewModels/PlanningPageViewModel.cs
> +                sender.SelectionStart = pos + 1;
I didn't get it what this block of code should do, maybe if you refactor It will become clearer.

2017-10-03 12:05 UTC, thiago-rocha commented
@gmojunior ready to review

2017-10-03 12:05 UTC, soutolucas approved these changes

2017-10-03 12:18 UTC, gmojunior approved these changes

2017-10-03 12:24 UTC, merged